

service: serverless-slack-lambda


provider:
  name: aws
  runtime: python3.7
  profile: serverless-admin
  region: eu-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "kms:Decrypt"
      Resource: "arn:aws:kms:#{AWS::Region}:#{AWS::AccountId}:key/*"

  environment:
    REGION: eu-west-2
    SLACK_WEBHOOK_URL: AQICAHgoSl426Ylg1Hv7LE9aQnWljgRNo0LVg59j/LZTvDWdtgEh3wkJQaL6YmB0X2Qnl7fyAAAAqTCBpgYJKoZIhvcNAQcGoIGYMIGVAgEAMIGPBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDG6cEBW7FkihsBSC+QIBEIBi5pZ/QeXBqgUZpRPrhiPKGa6PK/eWPNjeDKCJI+aVpqipdmtIvU4Ga9wKWx8/20cUKPjkIOpHWAIvL2OMQm68lrtJ7YwLjNxdV53dDMVLtAx/SIdusAxGp2zQUALxzJLX32c=
    SLACK_CHANNEL: webhook-test
    SLACK_USERNAME: notify_slack_test
    SLACK_EMOJI: ':aws:'



functions:
  slack-lambda:
    handler: handler.lambda_handler

    events:
      - sns: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:hello-world-python-dev-alerts-alarm
      - sns: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:hello-world-python-dev-alerts-insufficientData
      - sns: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:hello-world-python-dev-alerts-ok

plugins:
  - serverless-pseudo-parameters
